"""Persistent spatial contracts and pure SI math; no localization or ROS."""

from .anchors import (
    ANCHOR_KINDS,
    SurveyedAnchor,
    parse_surveyed_anchor,
    parse_surveyed_anchors,
    surveyed_anchor_as_mapping,
)
from .localize import LocalizationSolution, localize_from_fiducials, synthetic_observation
from .observation import FiducialObservation, parse_fiducial_observation, parse_fiducial_observations
from .contracts import (
    ANGLE_UNIT,
    LENGTH_UNIT,
    SPACE_SPATIAL_FIELDS,
    TIME_UNIT,
    SpatialContractError,
    apply_located_in_pose,
    apply_space_spatial_fields,
    located_in_endpoints_allowed,
    reject_non_space_spatial_fields,
)
from .pose import (
    LOCALIZATION_QUALITY,
    PoseUncertainty,
    RuntimePose,
    parse_runtime_pose,
    runtime_pose_as_mapping,
)
from .transforms import (
    Orientation,
    Pose,
    Position,
    SpatialTransformError,
    compose_chain,
    compose_pose,
    invert_pose,
    pose,
    pose_as_mapping,
    pose_from_mapping,
    transform_point,
    transform_pose,
)
from .units import (
    SpatialUnitError,
    as_meters,
    as_radians,
    format_angle,
    format_length,
    normalize_angle,
    normalize_length,
)

__all__ = (
    "ANCHOR_KINDS",
    "ANGLE_UNIT",
    "LENGTH_UNIT",
    "LOCALIZATION_QUALITY",
    "SPACE_SPATIAL_FIELDS",
    "TIME_UNIT",
    "FiducialObservation",
    "LocalizationSolution",
    "Orientation",
    "Pose",
    "PoseUncertainty",
    "Position",
    "RuntimePose",
    "SpatialContractError",
    "SpatialTransformError",
    "SpatialUnitError",
    "SurveyedAnchor",
    "apply_located_in_pose",
    "apply_space_spatial_fields",
    "as_meters",
    "as_radians",
    "compose_chain",
    "compose_pose",
    "format_angle",
    "format_length",
    "invert_pose",
    "localize_from_fiducials",
    "located_in_endpoints_allowed",
    "normalize_angle",
    "normalize_length",
    "parse_fiducial_observation",
    "parse_fiducial_observations",
    "parse_runtime_pose",
    "parse_surveyed_anchor",
    "parse_surveyed_anchors",
    "pose",
    "pose_as_mapping",
    "pose_from_mapping",
    "reject_non_space_spatial_fields",
    "runtime_pose_as_mapping",
    "surveyed_anchor_as_mapping",
    "synthetic_observation",
    "transform_point",
    "transform_pose",
)
